"""
build.py — FORTE packaging helper
==================================
Cleans previous build artefacts, then calls PyInstaller to produce a
self-contained binary in dist/FORTE/.

Usage:
    source venv/bin/activate
    python3 build.py
"""

import PyInstaller.__main__
import platform
import os
import shutil
import sys

APP_NAME   = "FORTE"
ENTRY_POINT = "forte/main.py"


def clean_build_dirs():
    """Remove build/, dist/, and any stale FORTE.spec generated by PyInstaller."""
    print("Cleaning build directories...")
    for d in ["build", "dist"]:
        if os.path.exists(d):
            shutil.rmtree(d)
    # Only remove a *generated* spec; keep the hand-crafted FORTE.spec
    generated = f"{APP_NAME}_generated.spec"
    if os.path.exists(generated):
        os.remove(generated)


def get_os_specific_args():
    """Return PyInstaller CLI args that differ per operating system."""
    system = platform.system()

    if system == "Linux":
        return [
            "--name",       APP_NAME,
            "--clean",
            "--windowed",                     # no console window
            "--hidden-import", "PyQt6",
            "--hidden-import", "ptyprocess",
            "--hidden-import", "pyte",
            "--add-data",  "images:images",   # icon assets
            "--add-data",  "examples:examples",  # bundled .f90 examples
        ]

    if system == "Darwin":                    # macOS
        return [
            "--name",       APP_NAME,
            "--clean",
            "--windowed",
            "--target-architecture", "universal2",
            "--hidden-import", "PyQt6",
            "--hidden-import", "ptyprocess",
            "--hidden-import", "pyte",
            "--add-data",  "images:images",
            "--add-data",  "examples:examples",
        ]

    if system == "Windows":
        return [
            "--name",       APP_NAME,
            "--clean",
            "--windowed",
            "--hidden-import", "PyQt6",
            "--hidden-import", "ptyprocess",
            "--hidden-import", "pyte",
            "--add-data",  "images;images",   # Windows separator is ;
            "--add-data",  "examples;examples",
        ]

    # Fallback — generic args
    return [
        "--name",  APP_NAME,
        "--clean",
        "--windowed",
        "--hidden-import", "PyQt6",
        "--hidden-import", "ptyprocess",
        "--hidden-import", "pyte",
    ]


def build():
    clean_build_dirs()

    args = get_os_specific_args()
    args.extend([
        "--noconfirm",
        ENTRY_POINT,
    ])

    print(f"Building {APP_NAME} for {platform.system()} …")
    print()

    try:
        PyInstaller.__main__.run(args)
        print()
        print(f"Build complete!")
        print(f"Executable located in: dist/{APP_NAME}/")
    except Exception as exc:
        print(f"Build failed: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    build()

